### PR TITLE
use publish confirms when republishing

### PR DESCRIPTION
**Pull request by timbu**

### CODE REVIEW

**Review by mattbennett — APPROVED** [review]
👍

**Comment by mattbennett** [comment]
Can we try one more thing? Using `nameko.amqp.get_producer` to get a producer but redeclaring the exchange using a bare kombu `Connection` i.e. not using the pool via `nameko.amqp.get_connection`

**Comment by timbu** [comment]
@mattbennett - looks like that will work. Should we leave the `transport_options` kwarg on the bare Connection ?

**Comment by mattbennett** [comment]
No need, since it only exists to declare the exchange and doesn't do any publishing to confirm.

**Review by mattbennett — APPROVED** [review]
👍

**Pull request merged**
